# Generated by Django 3.1.5 on 2021-01-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('capa', models.TextField()),
                ('ano', models.IntegerField()),
                ('diretor', models.TextField()),
                ('sinopse', models.TextField()),
                ('disponivel', models.BooleanField(default=False)),
            ],
        ),
    ]
